POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiZXhwIjoxNzA5MjQyOTcxLCJ1c2VySWQiOjF9.IaXPalgbHI50wvIL8HjJZh6e5MHIj8P2QNY0Of5lCzM

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2024-01-01T15:30:00.000Z"
}
